# -*- coding: utf-8 -*-
"""day-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m77k2mvlQRxR14yVaJFYx4-c03Q9fin3
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# ----------------------------
# Page Configuration
# ----------------------------
st.set_page_config(
    page_title="Male vs Female Classifier",
    page_icon="👨👩",
    layout="centered"
)

# ----------------------------
# CSS
# ----------------------------
st.markdown("""
<style>

.stApp{
    background:linear-gradient(135deg,#EEF6FF,#FFFFFF);
}

.block-container{
    background:white;
    border-radius:20px;
    padding:30px;
    box-shadow:0px 8px 20px rgba(0,0,0,0.12);
}

h1{
    text-align:center;
    color:#0F172A;
}

.stButton>button{
    width:100%;
    background:#2563EB;
    color:white;
    border-radius:12px;
    font-size:20px;
    font-weight:bold;
    padding:12px;
    border:none;
}

.stButton>button:hover{
    background:#1D4ED8;
}

.success-box{
    background:#DCFCE7;
    color:#166534;
    padding:15px;
    border-radius:12px;
    text-align:center;
    font-size:22px;
    font-weight:bold;
}

.info-box{
    background:#DBEAFE;
    color:#1E3A8A;
    padding:15px;
    border-radius:12px;
    text-align:center;
    font-size:22px;
    font-weight:bold;
}

.footer{
    text-align:center;
    margin-top:30px;
    color:gray;
}

</style>
""", unsafe_allow_html=True)

# ----------------------------
# Load Model
# ----------------------------
@st.cache_resource
def load_model():
    return tf.keras.models.load_model("/content/binary_image_classifier (1).keras")

model = load_model()

# ----------------------------
# Title
# ----------------------------
st.title("👨👩 Male vs Female Image Classifier")

st.write(
    "Upload a face image and click **Predict** to identify whether the image is classified as **Male** or **Female**."
)

# ----------------------------
# Upload Image
# ----------------------------
uploaded_file = st.file_uploader(
    "Choose an image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")

    st.image(image, caption="Uploaded Image", width=300)

    img = image.resize((150, 150))
    img = np.array(img) / 255.0
    img = np.expand_dims(img, axis=0)

    if st.button("Predict"):

        prediction = model.predict(img)

        score = float(prediction[0][0])

        st.write(f"Prediction Score: **{score:.4f}**")

        if score >= 0.5:
            confidence = score * 100

            st.markdown(
                f"""
                <div class='info-box'>
                👨 Prediction : <br><br>
                <b>MALE</b><br><br>
                Confidence : {confidence:.2f}%
                </div>
                """,
                unsafe_allow_html=True
            )

        else:
            confidence = (1 - score) * 100

            st.markdown(
                f"""
                <div class='success-box'>
                👩 Prediction : <br><br>
                <b>FEMALE</b><br><br>
                Confidence : {confidence:.2f}%
                </div>
                """,
                unsafe_allow_html=True
            )

        st.progress(confidence / 100)

st.markdown("<hr>", unsafe_allow_html=True)

st.markdown(
    "<div class='footer'>Developed using TensorFlow & Streamlit</div>",
    unsafe_allow_html=True
)